server:
  port: 8080
spring:
  h2:
    console:
      enabled: false
      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username : root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ssafy123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb