spring:
  profiles:
    active:
      - local
      - common
    group:
      local:
        - db-local
        - security-local
      prod:
        - db-prod
        - security-prod
    include:
      - db
      - security

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: ssafy123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
    expiration: 60000
    refresh-token:
      expiration: 6040000000

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: a069661d45c92aa53c90918fbe2be8a3  # rest api key
            client-secret: VjnJJiwISfTlM0rc8XaKSnD5h2anH9UT # secret key
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email, birthday
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kauth.kakao.com/v2/user/me
            user-name-attribute: id
  data:
    redis:
      host: 127.0.0.1
      port: 6379
logging:
  level:
    com: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: debug

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com: info